# Generated by Django 5.1.7 on 2025-03-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='rejected_by_l1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
