# Generated by Django 5.1.7 on 2025-03-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_uploadedfile_rejected_by_l1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='is_valid_format',
            field=models.BooleanField(default=False),
        ),
    ]
