# Generated by Django 5.1.7 on 2025-05-02 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_uploadedfile_approved_at_uploadedfile_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='sent_to_l1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files_for_approval', to=settings.AUTH_USER_MODEL),
        ),
    ]
