# Generated by Django 5.1.7 on 2025-05-07 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_uploadedfile_sent_to_l1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='sent_to_l1',
        ),
    ]
