# Generated by Django 5.1.7 on 2025-05-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_uploadedfile_sent_to_l1'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='is_split',
            field=models.BooleanField(default=False),
        ),
    ]
