# Generated by Django 5.1.7 on 2025-09-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_uploadedfile_is_split'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('process', models.CharField(max_length=100)),
                ('pending', models.IntegerField(default=0)),
                ('approved', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('date', 'process')},
            },
        ),
    ]
