# Generated by Django 5.1.7 on 2026-08-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_media_folders'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='process',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
