# Generated by Django 5.1.7 on 2026-08-24 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_uploadedfile_location_uploadedfile_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='l1_status',
            field=models.CharField(blank=True, choices=[('lock', 'Lock'), ('unlock', 'Unlock')], default='', max_length=6),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='l1_status_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='l1_status_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='l1_status_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
