# Generated by Django 5.1.7 on 2026-09-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_storedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='delivery_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='last_delivery_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='last_delivery_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
