# Generated by Django 5.1.7 on 2026-09-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_uploadedfile_delivery_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='hrms_notified_key',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
