"""
Django settings for UploadData project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

from celery.schedules import crontab
import os

from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load the project-root .env file. Real environment variables take precedence,
# so docker-compose `environment:` entries still win over anything set here.
load_dotenv(BASE_DIR / '.env')
LOGIN_URL = '/login/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
AUTH_USER_MODEL = 'users.User'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#1#*p7ua#&3n#gxjswc3g0pks7q+^e3&76l8^gzf8q_!f-6q(t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '0.0.0.0', '127.0.0.1', '10.140.28.7', '172.20.122.231']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_results',
    'users',
]

# Set custom login and logout redirects
LOGIN_URL = 'user_login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'user_login'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'UploadData.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'UploadData.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# PostgreSQL whenever POSTGRES_DB is set, which docker-compose always does.
# SQLite is kept as the fallback so a bare checkout, and the test suite, still
# run without the stack up.
#
# The move off SQLite is not cosmetic. Under the rollback journal every write
# takes an exclusive lock on the whole file, and gunicorn's workers, the Celery
# worker, django_celery_results and the HRMS watcher all write to it at once -
# on a Windows host, through a Docker bind mount, where POSIX advisory locks are
# not reliable. That is what surfaced as "database is locked" in the HRMS task.
# if os.environ.get('POSTGRES_DB'):
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.postgresql',
#             'NAME': os.environ['POSTGRES_DB'],
#             'USER': os.environ.get('POSTGRES_USER', 'downtime'),
#             'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
#             'HOST': os.environ.get('POSTGRES_HOST', 'postgres_down'),
#             'PORT': os.environ.get('POSTGRES_PORT', '5432'),
#             # Left at 0 deliberately: gunicorn workers and long-lived Celery
#             # prefork children would otherwise hold connections open across the
#             # minute-long HRMS upload. Raise it once that is measured, not before.
#             'CONN_MAX_AGE': int(os.environ.get('POSTGRES_CONN_MAX_AGE', '0')),
#         }
#     }
# else:
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.sqlite3',
#             'NAME': BASE_DIR / "db.sqlite3",
#             'OPTIONS': {
#                 # WAL lets readers run while a write is in progress, and 30s is
#                 # long enough to ride out a slow writer. Without these the
#                 # fallback would carry the same defect being migrated away from.
#                 'timeout': 30,
#                 'init_command': 'PRAGMA journal_mode=WAL;',
#             },
#         }
#     }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / "db.sqlite3",
        'OPTIONS': {
            # WAL lets readers run while a write is in progress, and 30s is
            # long enough to ride out a slow writer. Without these the
            # fallback would carry the same defect being migrated away from.
            'timeout': 30,
            'init_command': 'PRAGMA journal_mode=WAL;',
        },
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_I18N = True

# settings.py
TIME_ZONE = 'Asia/Kolkata'  # Set to IST
USE_TZ = True  # Keep this enabled for database consistency
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email settings are read from the environment (see .env / .env.example).
# EMAIL_HOST_PASSWORD is a Gmail App Password and is never committed to source.
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')  # e.g., for Gmail
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').strip().lower() in ('1', 'true', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'digx.automation@iccs.in')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# Only used when EMAIL_BACKEND is the filebased backend (local development).
EMAIL_FILE_PATH = os.environ.get(
    'EMAIL_FILE_PATH', os.path.join(BASE_DIR, 'logs', 'sent_emails')
)

# Celery. The default is the docker-compose service name; set CELERY_BROKER_URL in
# .env to point at a host-mapped port when running outside the compose network.
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://redis_down:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'django-db')

# Beat resolves crontab times against this, and it defaults to UTC. Without it
# the 10:00 reminders below would go out at 15:30 IST.
CELERY_TIMEZONE = TIME_ZONE

# Who the daily pending reminders go to. Overridable from the environment so a
# change of owner does not need a code change.
L1_PENDING_NOTIFY_EMAIL = os.environ.get(
    'L1_PENDING_NOTIFY_EMAIL', 'santosh.kumar@iccs.in'
)
L2_PENDING_NOTIFY_EMAIL = os.environ.get(
    'L2_PENDING_NOTIFY_EMAIL', 'akshat.bhatnagar@iccs.in'
)

# Standing recipients of every HRMS upload success/failure notice, as a
# comma-separated list. The uploader of the file is always added on top, so an
# empty value still notifies the person who uploaded it.
HRMS_NOTIFY_EMAILS = [
    address.strip()
    for address in os.environ.get('HRMS_NOTIFY_EMAILS', '').split(',')
    if address.strip()
]

# Files uploaded by regular users are not mailed about at upload time; a single
# digest per stage goes out the next morning and every morning after that, for
# as long as the file is still waiting. Anything already actioned drops out of
# the queries in users.tasks, so an approved file is never mentioned.
CELERY_BEAT_SCHEDULE = {
    'l1-pending-lock-unlock-10am': {
        'task': 'users.tasks.notify_l1_pending_files',
        'schedule': crontab(hour=10, minute=0),
    },
    'l2-pending-approval-10am': {
        'task': 'users.tasks.notify_l2_pending_files',
        'schedule': crontab(hour=10, minute=0),
    },
}
